Update strings.xml
Moriafly/SaltPlayerSource pull request #608
Opened 2023-06-30 18:14 UTC by KomiyaTaichi

更新繁體語言（string name怎麼全變成string 名字了...？）

2023-07-01 04:45 UTC, Moriafly requested changes
这是自动化的吗？不该将 name 改成名字

2023-07-01 08:06 UTC, KomiyaTaichi commented
我複製進去它直接變成這個了，你先看看能不能用吧o(´^｀)o

2023-07-01 08:10 UTC, KomiyaTaichi commented
重新編輯了@Moriafly

2023-07-01 08:19 UTC, KomiyaTaichi commented
大概知道是什麼原因了，是某個腳本的問題。現在沒事了

2023-07-08 05:29 UTC, KomiyaTaichi commented
@Moriafly 不合併的話，以後就不提交了 0.0

2023-07-09 08:41 UTC, Moriafly commented
🌹

2023-07-09 08:41 UTC, merged